### ISSUE TITLE
Tailwind classes are not inherited to child elements

### ISSUE THREAD

**Issue by iBobik** [vue-email/vue-email#121]
Classes translation to inline styles is not intuitive and when there is inheritance expected, it will behave unexpectly. Also Tailwind text size classes does not override default font-size.

```
<template>
  <e-html lang="cs">
    <e-tailwind>
      <div class="text-center text-base">
        <e-text class="text-base">Only this text have text-base applied</e-text>
        <e-text>This text should have text-base applied, but does not.</e-text>
      </div>
    </e-tailwind>
  </e-html>
</template>
```

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html id="__vue-email" lang="cs" dir="ltr">
  <div style=" font-size:1rem;line-height:1.5rem;text-align:center">
    <p data-id="__vue-email-text" style="font-size:14px;line-height:24px;margin:16px 0; font-size:1rem;line-height:1.5rem">Only this text have text-base applied</p>
    <p data-id="__vue-email-text" style="font-size: 14px; line-height: 24px; margin: 16px 0;">This text should have text-base applied, but does not.</p>
  </div>
</html>
```

If it cannot be fixed, there should be easy to understand explanation in docs.

**Comment by Flowko** [comment]
yeah thats not possible rn, cus we have to go through the tempalte and convert all the tailwind classes into styles, and then on each element that has tailwind classes we add next to it the converted styles, adding the ability to look for nested elements, adds a bit of complexity to it, but will keep this issue open, as we might try to resolve it some time

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
