### ISSUE TITLE
Vue peer dependency is locked to "3.3.4"

### ISSUE THREAD

**Issue by romeromembersy** [vue-email/vue-email#122]
For some reason the peer dependency for `vue` is locked to `3.3.4`, this is breaking the builds.

The dependency should be `^3.3.4`

**Comment by Flowko** [comment]
can u show me an example of a build breaking

**Comment by BayBreezy** [comment]
What i did to get pass this error was to add this to my package.json file

```json
"overrides": {
  "vue": "latest"
}
```

Visit here to see full explanation of overrides: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by Flowko** [comment]
can you test with `"vue-email": "npm:vue-email-edge@0.8.0-28377777.28f5ebc",`

**Comment by romeromembersy** [comment]
Thank you for fixing this, I cannot actually test that because I'm using the `@vue-email/nuxt` package.

**Comment by Flowko** [comment]
try this `npm:@vue-email/nuxt-edge@0.8.1-28377783.9298144`

**Comment by romeromembersy** [comment]
It got further this time, but it failed with:

```
440
Build failed with status: FAILURE and message: npm ERR! code ETARGET
441
npm ERR! notarget No matching version found for @vue-email/compiler@0.8.0-28377780.eecfece.
442
npm ERR! notarget In most cases you or one of your dependencies are requesting
443
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Flowko** [comment]
let me do a quick release

**Comment by Flowko** [comment]
can u try `"@vue-email/nuxt": "0.8.2"`

**Comment by romeromembersy** [comment]
It worked, thank you very much

**Comment by Flowko** [comment]
thanks for reporting it

**Comment by BayBreezy** [comment]
Yay! I also had to install the compiler separately. Thanks for the fix @Flowko

**Comment by Flowko** [comment]
If u are using nuxt, no need to use the compiler, u can just use what comes with nuxt, but glad it worked for you
