### ISSUE TITLE
How to improve html→text conversion

### ISSUE THREAD

**Issue by iBobik** [vue-email/vue-email#132]
Hi,
in some parts I want to influence how e-mail plaintext version is generated.

I see config is hardcoded, so there are not many ways how to do it.

Possible features what could help:
- custom [config for html-to-text](https://www.npmjs.com/package/html-to-text#options) (global and in Vue template)
- add `<html-only>` and `<text-only>` for use in Vue templates
- custom formatter in Vue template - `<table plaintext-format="dataTable" :plaintext-options"{ leadingLineBreaks: 1, trailingLineBreaks: 1 }>"`

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/

**Comment by iBobik** [comment]
@Flowko I does not see how this is solved in new version. Could you link me there, please?
