### ISSUE TITLE
ECodeBlock rendering issues in combination with ETailwind

### ISSUE THREAD

**Issue by Mokkapps** [vue-email/vue-email#141]
## Actual Behavior

HTML tags are not correctly rendered in a `ECodeBlock` is inside `ETailwind`, for examle it render `div>` instead of `</div>`

![image](https://github.com/vue-email/vue-email/assets/3127210/dd63376a-3234-4b39-bd33-42aa78f880dc)

```
<script setup lang="ts">
const code1 = `<template>
<div>
  <h2>Child</h2>
  <slot name="top" />
  <slot name="bottom" />
</div>
</template>`;
</script>

<template>
  <ETailwind>
    <EHtml>
      <EHead />
      <title>Title</title>
      <EPreview>Preview</EPreview>
      <EBody class="mx-auto my-auto w-full bg-white font-sans">
        <EContainer
          class="mx-auto my-[40px] w-full max-w-[650px] p-[20px] md:p-7"
        >
          <ESection>
            <ECodeBlock :code="code1" lang="vue" theme="poimandres" />
          </ESection>
        </EContainer>
      </EBody>
    </EHtml>
  </ETailwind>
</template>
```

## Expected Behavior

`ECodeBlock` is correctly rendered inside `ETailwind`

## Reproduction

https://stackblitz.com/edit/github-jwbr3n?file=emails%2FTest.vue

**Comment by Flowko** [comment]
should be fixed in `0.8.12` , thanks for the reproduction!

![image](https://github.com/vue-email/vue-email/assets/35883748/051dd5c0-23b4-44b0-b2c4-d52b46b62777)
