### ISSUE TITLE
The `html` field must be a `string`.

### ISSUE THREAD

**Issue by tylerprimmer** [vue-email/vue-email#155]
I am using Nuxt 3 with Vue Mail and I am getting the error, The `html` field must be a `string`.

![CleanShot 2024-02-10 at 22 27 41@2x](https://github.com/vue-email/vue-email/assets/70348541/b6a348c9-ad1a-422d-ba03-e9ca79eb0279)

**Comment by Flowko** [comment]
https://vuemail.net/ssr/nuxt#server-api

Its, `template.html`

**Comment by tylerprimmer** [comment]
Even with this I am getting: 

"data": {
        "data": null,
        "error": {
            "name": "validation_error",
            "statusCode": 422,
            "message": "Missing `html` or `text` field."
        }
    }

**Comment by Flowko** [comment]
@tylerprimmer you are missing `await` in front of `useCompiler`
