### ISSUE TITLE
Bundle size / Tree shaking ?

### ISSUE THREAD

**Issue by iliane5** [vue-email/vue-email#157]
Hi!

Thanks for the great work on the package

I've noticed that vue-email uses shiki for syntax highlighting on the Code Block component which I'll admit looks great but adds nearly 7.7Mb (gzipped) to the package even without using any Code Block component. Are there any plans on maybe dropping the code block or moving it to a separate package, etc?

**Comment by rahulkumarsingh73690** [comment]
+1

**Comment by MickL** [comment]
Is this project still maintained @Flowko

**Comment by Flowko** [comment]
currently there's no plan to drop shiki, but thanks for the feedback, @MickL happpy to receive pull request to fix these issues, im currently bussy with full time work, so i dont have much time to do big integration or changes to the library, the library rn its in a state that works for most cases.

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
