### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by Giildo** [vue-email/vue-email#159]
Hello,

I've just discovered your project & I like this!

I saw problems in the documentation in the "NodeMailer" part : 
- For the point "2. Create an email using Vue" you use kebab-case for the tag and in the another parts you use PascalCase.
- For the point "Step 3: Convert to HTML and send email" for NodeJS you import "config" with "vue-email/compiler" & not with "@vue-email/compiler"

**Comment by pochat** [comment]
I also experienced errors in the docs. For example, in Nuxt 3, this line does not work:
`import { useCompiler } from '#vue-email'
`

Error:
TS2307: Cannot find module #vue-email or its corresponding type declarations.

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
