### ISSUE TITLE
Incorrect rendering of markdown

### ISSUE THREAD

**Issue by ach1m-dev** [vue-email/vue-email#173]
Hi,

the rendering related to paragraphs in markdown seems to be partially incorrect.  

So far we've identified the following:

<details>
  <summary>Line breaks are not being rendered</summary>

  ```md
  Some line with line break  
  Some other line with line break  
  Another line without linebreak
  ```

  Current rendering

  ```html
  <p>
    Some line with line break
  </p>
  <p>
    Some other line with line break
  </p>
  <p>
    Another line without linebreak
  </p>
  ```

  Expected rendering

  ```html
  <p>
    Some line with line break<br>
    Some other line with line break<br>
    Another line without linebreak
  </p>
  ```
</details>

<details>
  <summary>Paragraphs are not being rendered if a line starts with an asterisk</summary>

  ```md
  Some paragraph
  
  **Some other** paragraph
  
  *Another* paragraph
  ```

  Current rendering

  ```html
  <p>
    Some line with line break
  </p>
  <strong>Some other</strong> paragraph <em>Another</em> paragraph
  ```

  Expected rendering

  ```html
  <p>
    Some line with line break
  </p>
  <p>
    <strong>Some other</strong> paragraph
  </p>
  <p>
    <em>Another</em> paragraph
  </p>
  ```
</details>

Reproduction: <https://stackblitz.com/edit/nuxt-starter-jwjmve?file=emails%2FMail.vue>

We could at least create some more test cases within [`Markdown.spec.ts`](https://github.com/vue-email/vue-email/blob/main/tests/Markdown.spec.ts) for a start.  
We'd then try to correct the rendered output and create a pull request if that's been successful.

**Comment by ach1m-dev** [comment]
The PR of @vjanoch (https://github.com/vue-email/vue-email/pull/172) covers the first issue.

After noticing that there's more we've decided to create this issue.

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
