### ISSUE TITLE
Accept ETailwind without config

### ISSUE THREAD

**Issue by admiralsemu** [vue-email/vue-email#176]
Currently when using `<ETailwind>` without a config an error is thrown: 

```WARN  [Vue warn]: Unhandled error during execution of setup function at <ETailwind>```

An option for accepting the base TailwindCSS config without modification should be allowed.

**Comment by Dromi-dror** [comment]
hello world

**Comment by Dromi-dror** [comment]
comment

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
