### ISSUE TITLE
[Feature] Auto import only needed components

### ISSUE THREAD

**Issue by geminigeek** [vue-email/vue-email#179]
hi,

i am setting it up like here https://www.vuemail.net/getting-started/ssr , i have three templates all of them are compiling while i just want to wok on one "WelcomeEmail" ? here is the output when i set verbose true .

```

💌 Generating output
🚧 Compiling TailwindEmail file
🚧 Compiling VerifyEmail file
🚧 Compiling WelcomeEmail file
🌎 Injecting translations
🎉 Rendering template WelcomeEmail
```

this is my config 

```
const vueEmail = config("./templates", {
  verbose: true,
  
})
```

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
