### ISSUE TITLE
Special Characters in template result in an error

### ISSUE THREAD

**Issue by Niki2k1** [vue-email/vue-email#182]
When using any special characters in the 0.8.0 beta
I get the following Error:

```
Error loading component [TypeError: invalid utf-8 sequence of 1 bytes from index 3143] {
  code: "ERR_MODULE_NOT_FOUND"
}
```

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
