### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by Corentin7301** [vue-email/vue-email#187]
Hello,
I've an issue in Nuxt v3.11.2 and vue-email/nuxt v0.8.19.

When I run the dev server, I've:
` WARN  No driver set for storage mount point "50".`
from 50 to 950, so I this is Tailwind colors.

And:
` ERROR  [uncaughtException] callback is not a function at process.processTicksAndRejections (node:internal/process/task_queues:77:11)`

And the server refuse to run.

I don't understand where can it come from...

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
