### ISSUE TITLE
Build fail on cloudflare on bigger projects

### ISSUE THREAD

**Issue by samulefevre** [vue-email/vue-email#191]
Hello, when i use : rollupConfig: {
      plugins: [vue()]
    },

I got error : 
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

Nuxt: 3.12.2
Modules: 
'@nuxthub/core',
    'nuxt-auth-utils',
    '@nuxt/test-utils/module',
    '@nuxt/eslint',
    // you need to register @nuxt/content before @nuxt/ui otherwise Tailwind CSS classes won't be parsed in your .md and .yml files.
    '@nuxt/content',
    '@nuxt/ui',
    '@nuxt/image',
    '@nuxtjs/i18n',
    '@vueuse/nuxt',

**Comment by Flowko** [comment]
need a reprodcution and also did you try to remove/include vue-email to see if its what breaking yout projecy ?

**Comment by samulefevre** [comment]
I removed vue-email, the error still occur, so no vue-email. Can be nuxt version or a module. Sorry

**Comment by Flowko** [comment]
you better check https://github.com/vitejs/vite-plugin-vue and thank you

**Comment by samulefevre** [comment]
i removed rollupconfig to test.

**Comment by samulefevre** [comment]
not found the problem, but closing issue as not related to vue-email.

**Comment by samulefevre** [comment]
problem solved, was node version on cloudflare, changed 18.17.1 to 20.7.0

**Comment by Flowko** [comment]
Glad you found a fix for it
