### ISSUE TITLE
Unknown type error

### ISSUE THREAD

**Issue by HugoRCD** [vue-email/vue-email#192]
Any idea why my IDE is telling me this (WebStorm)?

![CleanShot 2024-06-25 at 18 12 08](https://github.com/vue-email/vue-email/assets/71938701/10c2b2a4-9eef-4af1-b0ac-9151aa05add2)

**Comment by Flowko** [comment]
its best to check with either https://github.com/unjs/nitro or https://github.com/vitejs/vite-plugin-vue as this not related to `vue-email`
