### ISSUE TITLE
`Style` component is missing from exports

### ISSUE THREAD

**Issue by abdul-alhasany** [vue-email/vue-email#195]
Hi

As per [documentation](https://vuemail.net/components/style), I added this code to my nuxt project:
```js
<script setup lang="ts">
import { Head, Style } from '@vue-email/components'
</script>
```
But I am receiving this error:
> The requested module '/_nuxt/node_modules/.cache/vite/client/deps/@vue-email_components.js?v=33decdef' does not provide an export named 'Style'.

All other components are imported without any issues.

**Comment by Flowko** [comment]
should be there in 0.0.18 version, thank you for reporting it

**Comment by abdul-alhasany** [comment]
Thanks for the quick response. I updated the package but still have the same issue. 
I removed `node_modules` folder and `pnpm-lock.yaml` then tried to insall again using `pnpm install` but I received this error:

> ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@vue-email/render@workspace:*" is in the dependencies but no package named "@vue-email/render" is present in the workspace
> 
> This error happened while installing the dependencies of @vue-email/components@0.0.18 

I ran `pnpm install` with version `0.0.17` and it is working fine.

**Comment by Flowko** [comment]
weird, something has to do with how it was published, could you check 0.0.19 ?

**Comment by Flowko** [comment]
btw, did you have `@vue-email/render` installed or not ?

**Comment by abdul-alhasany** [comment]
Now it is working with version `0.0.19`. Thanks.

Yes, I have installed `@vue-email/render`
