### ISSUE TITLE
Warning: The CJS build of Vite's Node API is deprecated

### ISSUE THREAD

**Issue by fayazara** [vue-email/vue-email#196]
I keep getting this warning, pretty sure its not breaking anything, just logging this for future enhancement

[2:17:54 PM]  WARN  The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

**Comment by fayazara** [comment]
@Flowko just checked this is breaking the the production build when I deploy it with Nuxt on cloudflare pages.

Let me create a reproduction, will share it shortly

**Comment by Flowko** [comment]
would love to see a reproduction, but i dont think its related to vue-email as its a vite related thing, so more related to `@vitejs/plugin-vue`
