### ISSUE TITLE
`plainText: true` in `render` method generates HTML 

### ISSUE THREAD

**Issue by Mokkapps** [vue-email/vue-email#197]
## Current Behavior

`plainText: true` in `render` method generates HTML 

## Expected Behavior

`plainText: true` in `render` method generates plain text 

## Reproduction

https://stackblitz.com/edit/vitejs-vite-rzhuuq?file=src%2FApp.vue

**Comment by Flowko** [comment]
hi, the second object you pass are the params of the component, it should be like this:
```
const plainText = ref('');

const onRender = async () => {
  plainText.value = await render(Email, {
	// ....props
}, {
    plainText: true,
  });
};
```

**Comment by Mokkapps** [comment]
> hi, the second object you pass are the params of the component, it should be like this:
> 
> ```
> const plainText = ref('');
> 
> const onRender = async () => {
>   plainText.value = await render(Email, {
> 	// ....props
> }, {
>     plainText: true,
>   });
> };
> ```
> 
> https://vuemail.net/getting-started/usage#_3-convert-to-plain-text

Yes, my fault. Thanks!
