### ISSUE TITLE
TypeScript issues with nitro rollupConfig

### ISSUE THREAD

**Issue by chang-ryan** [vue-email/vue-email#203]
I see we have this thing going on in order to get vue email to work

```js
import vue from '@vitejs/plugin-vue'

export default defineNuxtConfig({
  nitro: {
    rollupConfig: {
      plugins: [vue()]
    },
  },
})
```

however, it does not play very well with typescript

we get this error on the line `plugins: [vue()]`

```
Type instantiation is excessively deep and possibly infinite.ts(2589)
(alias) vue(rawOptions?: Options): Plugin<Api>
import vue
```

Any one have any leads here? I'm currently suppressing it with `@ts-expect-error` or `@ts-ignore`

**Comment by chang-ryan** [comment]
Suppressing it works fine. Everything builds, but I just wanted to make an issue here so we can track it. Happy to help out with some PRs too if needed

**Comment by juni0r** [comment]
Can confirm, having the exact same issue. Also went with `@ts-expect-error` for now.

**Comment by Flowko** [comment]
hi, i'll be closing this, as its not related to vue-email, please open an issue at https://github.com/vitejs/vite-plugin-vue/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen for them to check this out. thanks
