### ISSUE TITLE
Error while starting component render

### ISSUE THREAD

**Issue by medzhidov** [vue-email/vue-email#205]
What i did wrong? I start with `bun src/index.ts`

![CleanShot 2024-08-19 at 17 51 26](https://github.com/user-attachments/assets/c0ba17ab-87b4-497f-a83e-7e68c3e31d3c)

![CleanShot 2024-08-19 at 17 53 39](https://github.com/user-attachments/assets/b0236e0e-6d2f-4d60-83e1-b82702150882)

**Comment by toothlesstarantula** [comment]
Same here, I thought the render function was able to process vue SFC's correctly, but it appears that in the new version is missing this step if doesnt have the renderer installed (like vuePlugin on vite or nuxt3)

**Comment by Flowko** [comment]
this sadly no longer supported to be standalone compiler, it has to be used along side vite/nitro/nuxt to be able to render the components, as we no longer trying to build a "Custom" compiler
