### ISSUE TITLE
Typescript does not see mail templates

### ISSUE THREAD

**Issue by iBobik** [vue-email/vue-email#209]
Hi,
I use Nuxt with templates in the emails folder, but TS does not see it's type declarations when importer on the server:

> Cannot find module '../../../emails/OrderConfirmation.vue' or its corresponding type declarations.ts(2307)

![Snímek obrazovky 2024-09-09 v 20 18 22](https://github.com/user-attachments/assets/9135dc96-16bb-45ec-a868-3f6d55d527ee)

However it works in both local node and production Cloudflare environments, just TS complains about it.

**Comment by DavidDeSloovere** [comment]
Can you show more code? Maybe Nuxt and Vue version also?

**Comment by iBobik** [comment]
> Can you show more code? Maybe Nuxt and Vue version also?

What exactly are you interested in? I cannot share the repo. Also I was not able to reproduce it in the Codesandbox.

**Comment by DavidDeSloovere** [comment]
This works for me

![image](https://github.com/user-attachments/assets/f73c1121-8da7-4593-b9d9-2d360a526a5c)

**Comment by Flowko** [comment]
dont think this is related to vue-email at all, its more related to the framework you are using

**Comment by iBobik** [comment]
> dont think this is related to vue-email at all, its more related to the framework you are using

We use Nuxt framework and this is Nuxt module. Nuxt has a Typescript as an primary supported compiler and linter. Modules are expected to work well with a TS. How could you think this issue is not related to the vue-email?

**Comment by DavidDeSloovere** [comment]
Although it might be related, it might not be caused by or solved by vue-email.
Maybe something in the template itself? As states, import works for me. So it not a general issue and probably something with code or other dependencies.

**Comment by Smef** [comment]
I have the same issue in a server route. This appears as an error in Jetbrains IDEs, but does not show as a problem in VS Code. The actual functionality is fine, and I can even command-click to jump to the component. TS is showing the error in the IDE, though.

`TS2307: Cannot find module ~/components/email/ContactFormEmail.vue or its corresponding type declarations.`
