### ISSUE TITLE
"Compile" Is NOT documented, component import not available in Node

### ISSUE THREAD

**Issue by arpowers** [vue-email/vue-email#213]
Just spent an hour on this: 

- You didn't document "compile" which is apparently the recommended way to render these things in Node
    -  this is the most typical use case for sending emails...
- You only document render which relies on the import of a component, which is not available in standard Node (no build system like vite)

**Comment by Flowko** [comment]
we no longer going that route, as we faced alot of issues tryiing to build a "custom" compiler that fits all shoes, we now only work with nuxt/nitro/vite compilers to handle the rest

**Comment by arpowers** [comment]
@Flowko ok I understand .... in that case, where is the doc for Node compilation using Vite or whatever? 

Am I wrong that Node compilation is the primary mode of use for this library?
