### ISSUE TITLE
Bug: `<br />` within `<p></p>` creates additional `<br />` at the end

### ISSUE THREAD

**Issue by MickL** [vue-email/vue-email#215]
Input:

```html
<p>
  a<br />
  b<br />
  c<br />
  d
</p>
```

Output:
```html
<p>
  a
   <br>
  b
   <br>
  c
   <br>
  d
   <br>
   <br>
   <br>
</p>
```

**Comment by MickL** [comment]
@Flowko Do you have the chance to look at it maybe? It is kind of a crucial bug because it adds <br>s everywhere

**Comment by kabarchonok** [comment]
I noticed that this only works if your content is wrapped in the `<Tailwind>` component. Inside the component, the `render` method from `dom-serializer` is used, and the `xmlMode` parameter is enabled. 
https://github.com/cheeriojs/dom-serializer?tab=readme-ov-file#xmlmode

Reference:
https://github.com/vue-email/vue-email/blob/9002af70381b19a1a3ae839617383d8806031984/packages/tailwind/src/index.ts#L126-L129

I’m not sure if this is justified, but maybe @Flowko was addressing a specific issue, so I don’t know if we can disable this parameter.

@MickL If you’re experiencing this issue without the <Tailwind> component, it would be helpful if you could provide a reproduction of the error in your project.

**Comment by MickL** [comment]
You are right, without the `<Tailwind>` wrapper the issue is not present. Unfortunately I am using Tailwind tho.

**Comment by kabarchonok** [comment]
While unraveling the thread of the bug, I came across a [similar problem](https://github.com/cheeriojs/dom-serializer/issues/1143) in the `dom-serializer` repository.

After studying `htmlparser2` and `dom-serializer` a bit, I think I realized that the reason is the absence of the middle link - [domhandler](https://github.com/fb55/domhandler).

I will try to solve this problem in the current PR as I have a similar bug, so I hope I am on the right track.

**Comment by MickL** [comment]
@kabarchonok Did you find anything out?

I invested a lot of time and effort in integrating vue-email and thening my mail tenplates but with this bug it is unusable. I cant send mails to my customers like this :(

**Comment by kabarchonok** [comment]
@MickL Hi there!

I fixed the single tag rendering and added a test, hopefully @Flowko will pay attention soon 🙏

**Comment by MickL** [comment]
Sounds amazing!
Unfortunately Flowko seems to be unavailable. May you release the fix on npm in the meantime?

**Comment by Flowko** [comment]
published to npm, please update to the latest versions, and thank you again @kabarchonok
