### ISSUE TITLE
[FEATURE] Support with Laravel

### ISSUE THREAD

**Issue by heychazza** [vue-email/vue-email#24]
Hey folks,

Not sure how, but it would be awesome if you guys were able to render and send emails for this library with Laravel. As currently the "out of the box" email system is super iffy.

Not sure how it would be done, but it would please many people

**Comment by Dave136** [comment]
Hi! Although we don't have any experience with Laravel at the moment, we appreciate your suggestion about adding this feature. 

We'll add it to our to-do list, thank you for your input.

**Comment by Flowko** [comment]
will close this as its not something we planning to resolve currently, if you have experience with laravel and u know of some ways to integrate vue email, send us a message, we have support for nodejs and nuxt, cus we depend heavily on npm packages, not sure how laravel handles that stuff on the server side.

## Our Ecosystem

| Package                     | Version                                                                                            |
| --------------------------- | :------------------------------------------------------------------------------------------------- |
| [Vue-Email](https://github.com/vue-email/vue-email)       | ![tres version](https://img.shields.io/npm/v/vue-email/latest.svg?label=%20&colorB=1fa669) |
| [Nuxt](https://github.com/vue-email/nuxt) | ![nuxt version](https://img.shields.io/npm/v/@vue-email/nuxt/latest.svg?label=%20&color=4f4f4f&logo=nuxt.js) |
[SSR Compiler](https://github.com/vue-email/compiler) | ![cientos version](https://img.shields.io/npm/v/@vue-email/compiler/latest.svg?label=%20&colorB=1fa669) |
| [CLI](https://github.com/vue-email/cli)       | ![tres version](https://img.shields.io/npm/v/@vue-email/cli/latest.svg?label=%20&colorB=1fa669) |
