### ISSUE TITLE
[FEATURE] Use Icons with Vue Email

### ISSUE THREAD

**Issue by TrippyCat423** [vue-email/vue-email#57]
Hi,

Seems like there is a bug when using Tailwind with Font Awesome.

When i am using Tailwind no Font Awesome icon gets displayed.
But when i move the icon out of the <ETailwind> block it works.

Wont be displayed:

```html

<ETailwind>
  <!-- some code -->
  <span class="fa-solid fa-house"></span>
</ETailwind>

```

Gets displayed:

```html

<ETailwind>
  <!-- some code -->
</ETailwind>
<span class="fa-solid fa-house"></span>

```

**Comment by Dave136** [comment]
Hi! @TrippyCat423, currently the usage of FA is not supported inside `<ETailwind>`, but we've planned add the FA integration. We'll work in this feature as soon possible.

Thanks!

**Comment by TrippyCat423** [comment]
Ok thanks.

**Comment by Flowko** [comment]
You can't use webfonts reliably in html emails. Some clients might respect and render them, but the majority don't.

you need to convert the icons into images, and then simply download the images and upload them into ur server or any storage provider, we'll try to find a way to integrate icons from https://icones.js.org/ into the vue-email, but its gonna take a bit of time

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
