### ISSUE TITLE
[FEATURE] UnoCSS Support

### ISSUE THREAD

**Issue by michealroberts** [vue-email/vue-email#67]
I know UnoCSS is a slight wrapper of Tailwind, but I wondered want the feasibility is to add UnoCSS as another supported CSS utility library?

**Comment by Flowko** [comment]
Thanks for the suggestion, indeed that would be a great addition, we will try to include it, but first we'll have to take care of some importnat issues, will keepyou updated here

**Comment by michealroberts** [comment]
@Flowko Thanks 🙏

**Comment by Flowko** [comment]
we just merged a new project rewrite, please do check the docs and the updated logic https://vuemail.net/
