### ISSUE TITLE
[Feature] Load Tailwind Config from project if available

### ISSUE THREAD

**Issue by Flowko** [vue-email/vue-email#72]
>It would be nice if other imports would be allowed too. I already have a tailwind config in the project, and if possible I don't want to duplicate it. (currently I'm importing it in the script and passing it as a prop) Or perhaps use a composable and in nuxt the useRuntimeConfig()

_Originally posted by @nandi95 in https://github.com/Dave136/vue-email/issues/64#issuecomment-1721503941_

TODO:
- [x] Update how the Tailwind component works
- [x] vue-email/nuxt#23
- [x] Update docs https://github.com/vue-email/docs/pull/5

**Comment by madebyfabian** [comment]
Would be highly appreciated! I can offer testing as soon as there is a pre-release.
