### ISSUE TITLE
[Feature] Vue email CLI

### ISSUE THREAD

**Issue by IgnisDa** [vue-email/vue-email#75]
I am primarily interested in an `export` command which will render all emails. Similar to the react-email [CLI](https://react.email/docs/cli#email-export).

**Comment by mklueh** [comment]
That would be indeed perfect. 
In my case those emails should not be part of any Vue application, but I like to render them and use them elsewhere

**Comment by IgnisDa** [comment]
for the time being, i use this script to render my emails:

```ts
import { mkdirSync } from "fs";
import { readdir, writeFile } from "fs/promises";
import { config } from "vue-email/compiler";

mkdirSync("./dist", { recursive: true });

const vueEmail = config("./templates", { verbose: false });

const main = async () => {
	const components = await readdir("./templates");
	for (const componentFile of components) {
		if (!componentFile.endsWith("vue")) continue;
		const html = await vueEmail.render(componentFile, null);
		const filename = componentFile.replace(".vue", "");
		await writeFile(`./dist/${filename}.html`, html);
	}
};

main().catch(console.error);
```

**Comment by Flowko** [comment]
available now, sorry about the delay.

try:
```bash [Terminal]
npx vue-email export
```

Option        | Default          | Description
-------------------------|-----------------|------------------
`--dir` | `emails` | The directory of the emails.
`--out` | `out` | The directory where the generated files should be placed.
`--pretty` | `false` | Minify or prettify the generated HTML file.
`--text` | `false` | Set output format as plain text.

more info:
docs: https://vuemail.net/plugins/cli
repo: https://github.com/vue-email/cli

**Comment by Flowko** [comment]
let me know if you got some other ideas of helpfull cli commands
