### ISSUE TITLE
[Feature] Add a 'style' tag for responsiveness. 

### ISSUE THREAD

**Issue by thomasruffier** [vue-email/vue-email#83]
Hello,
Is it possible to add a 'style' tag with media queries to manage behavior based on window width?

**Comment by Flowko** [comment]
you should be able to do that using the `Head` components
https://www.vuemail.net/components/head

**Comment by Flowko** [comment]
nvm, its not possible rn, but will try to add it in the near future, thanks for the feedback

**Comment by thomasruffier** [comment]
Ok, thanks!

**Comment by Flowko** [comment]
available on version `0.8.5` sorry for the delay!
https://vuemail.net/components/style
