### ISSUE TITLE
Brevo Integration

### ISSUE THREAD

**Issue by Ben-VP** [vue-email/vue-email#86]
Hey!

Would [Brevo](https://www.brevo.com/) be on your list to integrate with Vue email?

https://www.npmjs.com/package/@getbrevo/brevo

Cheers,

Ben

**Comment by Dave136** [comment]
Hi, the `vue-email` transform the template to `html`, you can pass the compiled template result throw `html`, or `htmlContent` option of the any library, i believe that you can use [SendSmtpEmail](https://github.com/getbrevo/brevo-node/blob/HEAD/docs/SendSmtpEmail.md#brevosendsmtpemail) function in this case. 

I'll hope helping you! Try and comment if it works for you, please.

**Comment by Niki2k1** [comment]
brevo also has an node package which you can use. You can send transactional mails with html instead of using an brevo template.
